# Site settings
show_downloads: false
title: "Tackle Documentation"
permalink: pretty
repository: konveyor/tackle-documentation
# If domain is created with CNAME file, baseurl="/"
# GH page server URLs: 185.199.111.153, 185.199.110.153, 185.199.109.153, 185.199.108.153
baseurl: /

logo: "assets/img/konveyor-logo-tackle.svg"
type: website
future: false

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# empty array for asciidoc
asciidoc: {}
# upstream doc attributes
asciidoctor:
  attributes:
  - title=Installing and using Tackle
  - context=tackle
  - description=Refactoring applications for Kubernetes
  - abstract=Tackle enables you to assess your applications for their suitability for replatforming on Kubernetes.
  - author=Tackle documentation team
  - showtitle=@
  - build=upstream
  - imagesdir=../modules/images
  - project-name=Tackle
  - ocp=OpenShift Container Platform
  - project-version=1.0
  - kebab=Options menu image:kebab.png[title="Options menu",height=20]
  safe: unsafe

exclude:
  - README.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
